spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/food-corner?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8"
    username: root
    password:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
    hiddenmethod:
      filter:
        enabled: true

#  sql:
#    init:
#      mode: always
  jpa:
    # Choose either MySQL 8 or MySQL 5 below
    # For MySQL 8
    database-platform: org.hibernate.dialect.MySQL8Dialect
    #For MySQL 5
    #database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true
#Cloudinary Properties
cloudinary:
  api-key: 587398618388114
  api-secret: ${CLOUDINARY_API_SECRET}
  cloud-name: dl72c1rli

#Logging Properties
logging:
  level:
    org:
      hibernate:
        type:
          descriptor: TRACE
        SQL: DEBUG
      nodeValue: WARN
    blog: WARN
server:
  port: 8080

#JWT Properties
jwt-secret:
  key: 5A7234753778214125442A472D4B6150645367566B59703373357638792F423F



